# Site Settings
title: BMGovernance | BMGovernance's blog
email: master@bmgovernance.com
description: BMGovernance's blog
baseurl: 
url: "https:bmgovernance.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: BMGovernance
user_description: This is BMGovernance's blog.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: BMGovernance
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
